### ISSUE TITLE
IFrame support in web payments

### ISSUE THREAD

**Issue by rsolomakhin** [w3ctag/spec-reviews#147]
Hello TAG!

I'm requesting a TAG review of:

  - Name: IFrame support in web payments
  - Specification URL: https://w3c.github.io/browser-payment-api/#paymentrequest-and-iframes
  - Example code: http://rsolomakhin.github.io/pr/iframe/
  - Primary contacts: @rsolomakhin, @zkoch
  - Relevant time constraints or deadlines: Would like to ship in M-56, so would prefer a review before January.

**Comment by dbaron** [comment]
At first glance, the spec seems a bit informal, i.e., lacking a clear processing model.  Such a model would make it clearer what happens in the case of nested iframes.  Is the <code>allowpaymentrequest</code> attribute needed on the iframe at each origin boundary between the browsing context that wants to be allowed to make payment requests and the toplevel browsing context, or is it needed on more or fewer iframes?

Also, why is this extending only <code>HTMLIFrameElement</code> and not also <code>HTMLFrameElement</code> and <code>HTMLObjectElement</code>?  Those are the three interfaces that have a <code>contentDocument</code> property.  That said, the [allegedly-deprecated](https://bugzilla.mozilla.org/show_bug.cgi?id=287465) ([the editor's draft](https://svgwg.org/svg2-draft/struct.html#InterfaceGetSVGDocument) sort of agrees) <code>getSVGDocument()</code> seems to be on 2 of the 3 (not <code>HTMLFrameElement</code>, but with <code>HTMLEmbedElement</code> added.  Maybe a common interface here is needed...

**Comment by domenic** [comment]
In particular the spec should be using https://html.spec.whatwg.org/#allowed-to-use instead of the undefined term "allowed to make payment requests".

**Comment by annevk** [comment]
FWIW, "allowed to use" and the general uplifting to HTML is https://github.com/w3c/browser-payment-api/issues/311.

**Comment by domenic** [comment]
See https://github.com/whatwg/html/issues/2112 for a discussion of making it easier for spec authors to ask the question "am I being invoked cross origin"

**Comment by travisleithead** [comment]
Reviewed at TAG Boston f2f. Should followup that @annevk and @domenic comments were addressed.

**Comment by travisleithead** [comment]
Also note from our [minutes](https://pad.w3ctag.org/p/2017-02-08-minutes.md): Resolved: Attribute proposed in the spec LGTM

**Comment by domenic** [comment]
In general this has been largely straightened out (as long as you ignore the references to the W3C HTML fork in the Payment Request, and use the corresponding definitions in the HTML Standard) by the heroic work of @zcorpan. He's also added web platform tests, which is super-great.

I still have an open action item to see if https://github.com/whatwg/html/issues/2112 is still worthwhile and worth pursuing further as something generally useful, but the payment request-specific stuff has been straightened out nicely for now.

**Comment by triblondon** [comment]
Extracting from the minutes: we spent some time figuring out whether this attribute was appropriate for the iframe tag or whether it belonged in the `sandbox` attribute as a directive.  It does seem correct to make it an attribute of the tag itself, since it is currently consistently the case that sandbox directives re-enable things that the presence of the `sandbox` attribute disables.

That wraps things up from a TAG review perspective
